### PR TITLE
Enable to run maven tests

### PR DESCRIPTION
**Pull request by nkzawa**
Hi.

I fixed some problems to run tests<del>, though tests themselves fail</del>.

`$ mvn test`

By the way, I intend to fix some more issues, so I want to hear your plans about this project if you have.

Thank you for your work.

### CODE REVIEW

**Comment by fatshotty** [comment]
Hi,
this project is a simple porting of the original project just for using with Maven in my personal projects.
I have no plans about this project.
I should merge latest changes but I have no time to work on it now.

Feel free to make changes on this project.
I could set you as collaborator if you want :)

**Comment by nkzawa** [comment]
Hi, thank you for your response.

I may add features the original repository doesn't support and a few big changes.
So I think it's better to wait and see whether it's good to merge these to your repo or not.
I will send you pull requests again when it's ok.

Socket IO v1.0 is about to be released, so that I also don't have a clear plan frankly :(

**Comment by fatshotty** [comment]
hello,
can I merge this pull request?

**Comment by nkzawa** [comment]
Yes, please.
Additionally, set up Travis CI and display a badge image on README If you can :)

**Comment by fatshotty** [comment]
merged with 23779ae63132c51c8bf25e52ff58e032f003f9ed

**Comment by fatshotty** [comment]
travis has been integrated ;)
thanks

**Pull request merged**
